[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

# Environment 1: Robot Code
[env:robot]
build_src_filter = -<*> +<robot.cpp>
lib_deps = 
    pololu/QTRSensors@^4.0.0

# Environment 2: PC Receiver Code
[env:receiver]
build_src_filter = -<*> +<receiver.cpp>